### ISSUE TITLE
twitter-rohith.py write issue

### ISSUE THREAD

**Issue by srinidhinandakumar** [srinidhinandakumar/PEPr_Project_Code#2]
The code looks excellent and super modular! @Rohithyeravothula 
I'm concerned about two things:-

1. Writing at the end of 1 cycle => 800 tweets, and there is no write if there's a keyboard interrupt between the cycle. We will lose a lot of data. Can we add a write to the excepts too? - when currently crawled tweets list is not null
2. What is your call on not writing to disk more frequently? Like - maybe every 200 tweets at least?

**Comment by srinidhinandakumar** [comment]
Another issue is the JSON being dumped as output are just JSON objects and not a list of JSON objects - inconsistent with previous version. Any reason why this is what we want to do?

**Comment by Rohithyeravothula** [comment]
I am not a big fan of writing list of JSON to file, mainly because it is difficult to club multiple files with this format, and secondly loading the data would require to read the entire file to memory and convert to list of JSONs which is not a viable solution when we have a huge amount of data

**Comment by Rohithyeravothula** [comment]
for point 1, keyboard interrupts are something that the crawler is not supposed to ideally experience, so I think we can ignore this as it will add an overhead of at most 15 min for every keyboard interrupt
for point 2 I think we can write to disk for every 200 tweets shouldn't be a problem.
